version: '3.8'

services:
  para-classifier:
    build: .
    ports:
      - "5002:5002"
    environment:
      - SECRET_KEY=your-super-secret-production-key
      - FLASK_DEBUG=false
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    container_name: para-classifier-app 