[build]
# builder = "DOCKERFILE"   # 移除此行，Railway将自动检测Dockerfile

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 'src.main:app'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "para-classifier"
source = "."

[services.variables]
PORT = "5002"
SECRET_KEY = "your-railway-secret-key"
FLASK_DEBUG = "False" 