[build]
# builder = "DOCKERFILE"   # 移除此行，Railway将自动检测Dockerfile

[deploy]
# startCommand 已被移除，将使用 Dockerfile 的 ENTRYPOINT
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "para-classifier"
source = "."

[services.variables]
PORT = "5002"
SECRET_KEY = "your-railway-secret-key"
FLASK_DEBUG = "False" 